Repository dusk-network/jubjub, pull requests merged in 2020-05, with the labels that each got.

#1 Dependency
  src/lib.rs
Labels: area:cryptography, type:refactor

#3 Update jubjub fork
  src/fr.rs
  src/lib.rs
Labels: area:cryptography

#2 Implement Generator
  src/lib.rs
Labels: enhancement, status:blocker, type:feature
